//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioInformatica.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Laboratorio", Namespace="http://schemas.datacontract.org/2004/07/Entidade")]
    [System.SerializableAttribute()]
    public partial class Laboratorio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProjetorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdAlunosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdComputadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Software1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Software2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Software3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Projetor {
            get {
                return this.ProjetorField;
            }
            set {
                if ((this.ProjetorField.Equals(value) != true)) {
                    this.ProjetorField = value;
                    this.RaisePropertyChanged("Projetor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdAlunos {
            get {
                return this.QtdAlunosField;
            }
            set {
                if ((this.QtdAlunosField.Equals(value) != true)) {
                    this.QtdAlunosField = value;
                    this.RaisePropertyChanged("QtdAlunos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdComputadores {
            get {
                return this.QtdComputadoresField;
            }
            set {
                if ((this.QtdComputadoresField.Equals(value) != true)) {
                    this.QtdComputadoresField = value;
                    this.RaisePropertyChanged("QtdComputadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO {
            get {
                return this.SOField;
            }
            set {
                if ((object.ReferenceEquals(this.SOField, value) != true)) {
                    this.SOField = value;
                    this.RaisePropertyChanged("SO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Software1 {
            get {
                return this.Software1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Software1Field, value) != true)) {
                    this.Software1Field = value;
                    this.RaisePropertyChanged("Software1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Software2 {
            get {
                return this.Software2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Software2Field, value) != true)) {
                    this.Software2Field = value;
                    this.RaisePropertyChanged("Software2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Software3 {
            get {
                return this.Software3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Software3Field, value) != true)) {
                    this.Software3Field = value;
                    this.RaisePropertyChanged("Software3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Inserir", ReplyAction="http://tempuri.org/IService/InserirResponse")]
        bool Inserir(LaboratorioInformatica.ServiceReference.Laboratorio labInformatica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Inserir", ReplyAction="http://tempuri.org/IService/InserirResponse")]
        System.Threading.Tasks.Task<bool> InserirAsync(LaboratorioInformatica.ServiceReference.Laboratorio labInformatica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Listar", ReplyAction="http://tempuri.org/IService/ListarResponse")]
        LaboratorioInformatica.ServiceReference.Laboratorio[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Listar", ReplyAction="http://tempuri.org/IService/ListarResponse")]
        System.Threading.Tasks.Task<LaboratorioInformatica.ServiceReference.Laboratorio[]> ListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : LaboratorioInformatica.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<LaboratorioInformatica.ServiceReference.IService>, LaboratorioInformatica.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Inserir(LaboratorioInformatica.ServiceReference.Laboratorio labInformatica) {
            return base.Channel.Inserir(labInformatica);
        }
        
        public System.Threading.Tasks.Task<bool> InserirAsync(LaboratorioInformatica.ServiceReference.Laboratorio labInformatica) {
            return base.Channel.InserirAsync(labInformatica);
        }
        
        public LaboratorioInformatica.ServiceReference.Laboratorio[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<LaboratorioInformatica.ServiceReference.Laboratorio[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
    }
}
